apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "minipay"
  DB_USER: "minipay_app"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  DB_PASSWORD: "change_me_locally"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minipay-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minipay-api
  template:
    metadata:
      labels:
        app: minipay-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          command: ["sh", "-c", "until pg_isready -h postgres -p 5432; do echo waiting for postgres; sleep 2; done"]
      containers:
        - name: minipay-api
          image: minipay-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: minipay-api
spec:
  type: NodePort
  selector:
    app: minipay-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
